// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.

import {
  ethereum,
  JSONValue,
  TypedMap,
  Entity,
  Bytes,
  Address,
  BigInt
} from "@graphprotocol/graph-ts";

export class PairCreated extends ethereum.Event {
  get params(): PairCreated__Params {
    return new PairCreated__Params(this);
  }
}

export class PairCreated__Params {
  _event: PairCreated;

  constructor(event: PairCreated) {
    this._event = event;
  }

  get token0(): Address {
    return this._event.parameters[0].value.toAddress();
  }

  get token1(): Address {
    return this._event.parameters[1].value.toAddress();
  }

  get pair(): Address {
    return this._event.parameters[2].value.toAddress();
  }

  get param3(): BigInt {
    return this._event.parameters[3].value.toBigInt();
  }
}

export class Factory extends ethereum.SmartContract {
  static bind(address: Address): Factory {
    return new Factory("Factory", address);
  }

  allPairs(param0: BigInt): Address {
    let result = super.call("allPairs", "allPairs(uint256):(address)", [
      ethereum.Value.fromUnsignedBigInt(param0)
    ]);

    return result[0].toAddress();
  }

  try_allPairs(param0: BigInt): ethereum.CallResult<Address> {
    let result = super.tryCall("allPairs", "allPairs(uint256):(address)", [
      ethereum.Value.fromUnsignedBigInt(param0)
    ]);
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toAddress());
  }

  allPairsLength(): BigInt {
    let result = super.call("allPairsLength", "allPairsLength():(uint256)", []);

    return result[0].toBigInt();
  }

  try_allPairsLength(): ethereum.CallResult<BigInt> {
    let result = super.tryCall(
      "allPairsLength",
      "allPairsLength():(uint256)",
      []
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toBigInt());
  }

  createPair(tokenA: Address, tokenB: Address): Address {
    let result = super.call(
      "createPair",
      "createPair(address,address):(address)",
      [ethereum.Value.fromAddress(tokenA), ethereum.Value.fromAddress(tokenB)]
    );

    return result[0].toAddress();
  }

  try_createPair(
    tokenA: Address,
    tokenB: Address
  ): ethereum.CallResult<Address> {
    let result = super.tryCall(
      "createPair",
      "createPair(address,address):(address)",
      [ethereum.Value.fromAddress(tokenA), ethereum.Value.fromAddress(tokenB)]
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toAddress());
  }

  feeSetter(): Address {
    let result = super.call("feeSetter", "feeSetter():(address)", []);

    return result[0].toAddress();
  }

  try_feeSetter(): ethereum.CallResult<Address> {
    let result = super.tryCall("feeSetter", "feeSetter():(address)", []);
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toAddress());
  }

  feeTo(): Address {
    let result = super.call("feeTo", "feeTo():(address)", []);

    return result[0].toAddress();
  }

  try_feeTo(): ethereum.CallResult<Address> {
    let result = super.tryCall("feeTo", "feeTo():(address)", []);
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toAddress());
  }

  feeToBasisPoint(): BigInt {
    let result = super.call(
      "feeToBasisPoint",
      "feeToBasisPoint():(uint256)",
      []
    );

    return result[0].toBigInt();
  }

  try_feeToBasisPoint(): ethereum.CallResult<BigInt> {
    let result = super.tryCall(
      "feeToBasisPoint",
      "feeToBasisPoint():(uint256)",
      []
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toBigInt());
  }

  getPair(param0: Address, param1: Address): Address {
    let result = super.call("getPair", "getPair(address,address):(address)", [
      ethereum.Value.fromAddress(param0),
      ethereum.Value.fromAddress(param1)
    ]);

    return result[0].toAddress();
  }

  try_getPair(param0: Address, param1: Address): ethereum.CallResult<Address> {
    let result = super.tryCall(
      "getPair",
      "getPair(address,address):(address)",
      [ethereum.Value.fromAddress(param0), ethereum.Value.fromAddress(param1)]
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toAddress());
  }

  totalFeeBasisPoint(): BigInt {
    let result = super.call(
      "totalFeeBasisPoint",
      "totalFeeBasisPoint():(uint256)",
      []
    );

    return result[0].toBigInt();
  }

  try_totalFeeBasisPoint(): ethereum.CallResult<BigInt> {
    let result = super.tryCall(
      "totalFeeBasisPoint",
      "totalFeeBasisPoint():(uint256)",
      []
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toBigInt());
  }
}

export class ConstructorCall extends ethereum.Call {
  get inputs(): ConstructorCall__Inputs {
    return new ConstructorCall__Inputs(this);
  }

  get outputs(): ConstructorCall__Outputs {
    return new ConstructorCall__Outputs(this);
  }
}

export class ConstructorCall__Inputs {
  _call: ConstructorCall;

  constructor(call: ConstructorCall) {
    this._call = call;
  }

  get _feeSetter(): Address {
    return this._call.inputValues[0].value.toAddress();
  }

  get _totalFeeBasisPoint(): BigInt {
    return this._call.inputValues[1].value.toBigInt();
  }

  get _feeToBasisPoint(): BigInt {
    return this._call.inputValues[2].value.toBigInt();
  }
}

export class ConstructorCall__Outputs {
  _call: ConstructorCall;

  constructor(call: ConstructorCall) {
    this._call = call;
  }
}

export class CreatePairCall extends ethereum.Call {
  get inputs(): CreatePairCall__Inputs {
    return new CreatePairCall__Inputs(this);
  }

  get outputs(): CreatePairCall__Outputs {
    return new CreatePairCall__Outputs(this);
  }
}

export class CreatePairCall__Inputs {
  _call: CreatePairCall;

  constructor(call: CreatePairCall) {
    this._call = call;
  }

  get tokenA(): Address {
    return this._call.inputValues[0].value.toAddress();
  }

  get tokenB(): Address {
    return this._call.inputValues[1].value.toAddress();
  }
}

export class CreatePairCall__Outputs {
  _call: CreatePairCall;

  constructor(call: CreatePairCall) {
    this._call = call;
  }

  get pair(): Address {
    return this._call.outputValues[0].value.toAddress();
  }
}

export class SetFeeSetterCall extends ethereum.Call {
  get inputs(): SetFeeSetterCall__Inputs {
    return new SetFeeSetterCall__Inputs(this);
  }

  get outputs(): SetFeeSetterCall__Outputs {
    return new SetFeeSetterCall__Outputs(this);
  }
}

export class SetFeeSetterCall__Inputs {
  _call: SetFeeSetterCall;

  constructor(call: SetFeeSetterCall) {
    this._call = call;
  }

  get _feeSetter(): Address {
    return this._call.inputValues[0].value.toAddress();
  }
}

export class SetFeeSetterCall__Outputs {
  _call: SetFeeSetterCall;

  constructor(call: SetFeeSetterCall) {
    this._call = call;
  }
}

export class SetFeeToCall extends ethereum.Call {
  get inputs(): SetFeeToCall__Inputs {
    return new SetFeeToCall__Inputs(this);
  }

  get outputs(): SetFeeToCall__Outputs {
    return new SetFeeToCall__Outputs(this);
  }
}

export class SetFeeToCall__Inputs {
  _call: SetFeeToCall;

  constructor(call: SetFeeToCall) {
    this._call = call;
  }

  get _feeTo(): Address {
    return this._call.inputValues[0].value.toAddress();
  }
}

export class SetFeeToCall__Outputs {
  _call: SetFeeToCall;

  constructor(call: SetFeeToCall) {
    this._call = call;
  }
}

export class SetFeeToBasisPointCall extends ethereum.Call {
  get inputs(): SetFeeToBasisPointCall__Inputs {
    return new SetFeeToBasisPointCall__Inputs(this);
  }

  get outputs(): SetFeeToBasisPointCall__Outputs {
    return new SetFeeToBasisPointCall__Outputs(this);
  }
}

export class SetFeeToBasisPointCall__Inputs {
  _call: SetFeeToBasisPointCall;

  constructor(call: SetFeeToBasisPointCall) {
    this._call = call;
  }

  get _feeToBasisPoint(): BigInt {
    return this._call.inputValues[0].value.toBigInt();
  }
}

export class SetFeeToBasisPointCall__Outputs {
  _call: SetFeeToBasisPointCall;

  constructor(call: SetFeeToBasisPointCall) {
    this._call = call;
  }
}

export class SetTotalFeeBasisPointCall extends ethereum.Call {
  get inputs(): SetTotalFeeBasisPointCall__Inputs {
    return new SetTotalFeeBasisPointCall__Inputs(this);
  }

  get outputs(): SetTotalFeeBasisPointCall__Outputs {
    return new SetTotalFeeBasisPointCall__Outputs(this);
  }
}

export class SetTotalFeeBasisPointCall__Inputs {
  _call: SetTotalFeeBasisPointCall;

  constructor(call: SetTotalFeeBasisPointCall) {
    this._call = call;
  }

  get _totalFeeBasisPoint(): BigInt {
    return this._call.inputValues[0].value.toBigInt();
  }
}

export class SetTotalFeeBasisPointCall__Outputs {
  _call: SetTotalFeeBasisPointCall;

  constructor(call: SetTotalFeeBasisPointCall) {
    this._call = call;
  }
}
